#!/bin/bash
#Hello there, weary traveler, so you are looking for some code uh? well, be beware...

#cp allScripts/* /usr/local/bin/  #Old directory, too invasive for the system
mkdir $HOME/.bin
cp allScripts/* $HOME/.bin/
chmod +x $HOME/.bin/*
export PATH="$HOME/.bin:$PATH"
echo 'PATH="$HOME/.bin:$PATH"' >> $HOME/.bashrc
echo 'PATH="$HOME/.bin:$PATH"' >> $HOME/.zshrc
